# Generated by Django 5.1.6 on 2025-02-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        ('faculty', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.coremember'),
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.club'),
        ),
    ]
