# Generated by Django 5.1.6 on 2025-03-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('committees', '0001_initial'),
        ('faculty', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.coremember'),
        ),
        migrations.AddField(
            model_name='associations',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.coremember'),
        ),
        migrations.AddField(
            model_name='associations',
            name='faculty_incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='associationimage',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='committees.associations'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.associations'),
        ),
        migrations.AddField(
            model_name='nofification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.coremember'),
        ),
        migrations.AddField(
            model_name='nofification',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userprofile'),
        ),
    ]
