# Generated by Django 5.1.6 on 2025-02-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='faculty_incharge',
        ),
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('committees', 'Committees'), ('clubs', 'Clubs')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.associations'),
        ),
    ]
