# Generated by Django 5.1.6 on 2025-03-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
