# Generated by Django 5.1.6 on 2025-02-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_remove_club_faculty_incharge_associations_and_more'),
        ('events', '0002_alter_event_club'),
        ('members', '0002_alter_coremember_club_alter_member_club_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
