# Generated by Django 5.1.6 on 2025-03-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_associations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='associations',
            name='edit_request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edit_pending', 'Edit Request Pending'), ('delete_pending', 'Delete Request Pending')], default='pending', max_length=15),
        ),
    ]
