# Generated by Django 5.1.6 on 2025-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_associations_edit_request_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associations',
            name='edit_request_data',
        ),
        migrations.AlterField(
            model_name='associations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delete_pending', 'Delete Request Pending')], default='pending', max_length=15),
        ),
    ]
