# Generated by Django 5.1.6 on 2025-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_delete_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='associations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='association_images/'),
        ),
    ]
