# Generated by Django 5.1.6 on 2025-03-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_associations_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='association_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='committees.associations')),
            ],
        ),
    ]
