# Generated by Django 5.1.6 on 2025-03-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_userprofile_ssv_id'),
        ('committees', '0006_associationimage'),
        ('members', '0004_member_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nofification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.coremember')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userprofile')),
            ],
        ),
    ]
