# Generated by Django 5.1.6 on 2025-03-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_userprofile_preferences'),
        ('committees', '0006_associations_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userprofile'),
        ),
    ]
