# Generated by Django 5.1.6 on 2025-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_alter_announcement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='associations',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('Academic', 'Academic'), ('Technical', 'Technical'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Social', 'Social'), ('Other', 'Other')], default='None', max_length=30),
        ),
    ]
