# Generated by Django 5.1.6 on 2025-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('core_member', 'Core Member'), ('member', 'Member'), ('non_participating', 'Non Participating')], default='non_participating', max_length=20),
        ),
    ]
