# Generated by Django 5.1.6 on 2025-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ssv_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
