# Generated by Django 5.1.6 on 2025-02-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.userprofile')),
                ('position', models.CharField(max_length=100)),
                ('can_approve_members', models.BooleanField(default=False)),
                ('can_edit_events', models.BooleanField(default=False)),
                ('can_edit_club_page', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=list)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.club')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.userprofile')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notification_preference', models.CharField(choices=[('email', 'Email'), ('none', 'None')], max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.club')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'None')], max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userprofile')),
            ],
        ),
    ]
