# Generated by Django 5.1.6 on 2025-03-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coremember',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.associations'),
        ),
        migrations.AlterField(
            model_name='coremember',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
