# Generated by Django 5.1.6 on 2025-03-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_delete_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremember',
            name='club',
        ),
        migrations.RemoveField(
            model_name='member',
            name='club',
        ),
        migrations.AddField(
            model_name='coremember',
            name='assosiation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='member',
            name='assosiation',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
