# Generated by Django 5.1.6 on 2025-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_coremember_club_alter_coremember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'None')], default='email', max_length=10),
        ),
    ]
