# Generated by Django 5.1.6 on 2025-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_coremember_club_alter_member_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coremember',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
