# Generated by Django 5.1.6 on 2025-03-20 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_remove_associations_edit_request_data_and_more'),
        ('members', '0003_remove_coremember_club_remove_member_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremember',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.associations'),
        ),
    ]
