# Generated by Django 5.1.6 on 2025-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_coremember_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
