# Generated by Django 5.1.6 on 2025-03-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_coremember_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremember',
            name='club',
        ),
    ]
