# Generated by Django 5.1.6 on 2025-03-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_coremember_club_member_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremember',
            name='club',
        ),
        migrations.RemoveField(
            model_name='member',
            name='club',
        ),
    ]
