# Generated by Django 5.1.6 on 2025-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_coremember_assosiation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coremember',
            old_name='assosiation',
            new_name='association',
        ),
    ]
