# Generated by Django 5.1.6 on 2025-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_rename_assosiation_coremember_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coremember',
            old_name='association',
            new_name='assosiation',
        ),
    ]
