# Generated by Django 5.1.6 on 2025-03-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_association_coremember_assosiation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coremember',
            old_name='assosiation',
            new_name='association',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='assosiation',
            new_name='association',
        ),
    ]
