# Generated by Django 5.1.6 on 2025-03-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_userprofile_preferences'),
        ('committees', '0007_alter_announcement_created_by'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLockDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('online', 'Online'), ('auditorium', 'Auditorium'), ('open canteen', 'Open Canteen'), ('turf', 'Turf'), ('vidya vihar', 'Vidya Vihar')], default='online', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty')),
                ('assosiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.associations')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='Login.userprofile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.location')),
            ],
        ),
    ]
