# Generated by Django 5.1.6 on 2025-03-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='assosiation',
            new_name='association',
        ),
    ]
