# Generated by Django 5.1.6 on 2025-03-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='booked_from',
        ),
        migrations.RemoveField(
            model_name='location',
            name='booked_to',
        ),
        migrations.RemoveField(
            model_name='location',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('auditorium', 'Auditorium'), ('open canteen', 'Open Canteen'), ('turf', 'Turf'), ('vidya vihar', 'Vidya Vihar')], default='online', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('auditorium', 'Auditorium'), ('open canteen', 'Open Canteen'), ('turf', 'Turf'), ('vidya vihar', 'Vidya Vihar')], default='online', max_length=255),
        ),
        migrations.CreateModel(
            name='FacultyLockDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
    ]
