# Generated by Django 5.1.6 on 2025-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_assosiation_event_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='report_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
