# Generated by Django 5.1.6 on 2025-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('auditorium', 'Auditorium'), ('open canteen', 'Open Canteen'), ('turf', 'Turf'), ('vidya vihar', 'Vidya Vihar'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
