# Generated by Django 5.1.6 on 2025-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_location_booked_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultylockdate',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facultylockdate',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
