# Generated by Django 5.1.6 on 2025-03-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_facultylockdate_added_by_alter_event_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='club',
            new_name='assosiation',
        ),
    ]
