# Generated by Django 5.1.6 on 2025-02-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='locked_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
